name: Cargo build and test

on:
  push:
    paths:
      - 'api/**'
    branches:
      - main
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'
    branches:
      - main
      - 'api/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    strategy:
      toolchain:
        - stable
        - beta
        - nightly
    steps:
    - uses: actions/checkout@v4
    - name: Update to toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
